# Generated by Django 4.1.7 on 2023-04-20 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_rename_type_category_cate_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name_plural": "Transactions"},
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={"verbose_name_plural": "Wallets"},
        ),
    ]
