# Generated by Django 4.1.7 on 2023-04-19 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_profile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Profiles"},
        ),
    ]
